### ISSUE TITLE
Formatting does not happen when g++ is called with "-MMD" flag.

### ISSUE THREAD

**Issue by z3dd** [zaufi/pluggable-output-processor#12]
Python versions are 3.5.4 and 2.7.13
Linux 4.12.9-200.fc25.x86_64 

Example is in the attachment.

![screenshot16](https://user-images.githubusercontent.com/11164349/30372301-17682c1a-9886-11e7-8b1c-151d0f3c246b.png)

**Comment by zaufi** [comment]
Thanks for the report, I'll take a look as soon as possible

**Comment by zaufi** [comment]
That was intentionally (but by a mistake) ignored (as do-not-handle options, if found in CLI).
(that time I just add 'em to ignore list w/o reading which options could really produce an output to a terminal).
