### ISSUE TITLE
pip fails to install on mac os, missing dependency.

### ISSUE THREAD

**Issue by bogonetic** [zaufi/pluggable-output-processor#9]
When installing on Mac OS X via pip command "python setup.py egg_info" fails, ImportError: No module named 'termcolor'.

Simply doing a `pip install termcolor` before trying to install `outproc` fixes the issue. Perhaps `termcolor` could be added to the dependency list for the package?

**Comment by zaufi** [comment]
Hm... it is already [here](https://github.com/zaufi/pluggable-output-processor/blob/master/setup.py#L57) in `setup.py` and in [`requirements.txt`](https://github.com/zaufi/pluggable-output-processor/blob/master/requirements.txt#L2)…

but anyway, `setup.py` needs some renovation %) -- I'll do it soon...

**Comment by zaufi** [comment]
Ok, I've found a bug in dependencies. I'll fix it ASAP

**Comment by zaufi** [comment]
cycle dependency has been fixed and new version uploaded to PyPi
